name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Compile latex
        run: |
          ls ${{ github.workspace }}
          echo "Running latex"
          chmod +x "${GITHUB_WORKSPACE}/.github/latexcompile.sh
          ${GITHUB_WORKSPACE}/.github/latexcompile.sh -b -r -g -s ${GITHUB_WORKSPACE}/main.tex
          
