name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Compile latex
        run: |
          ls ${{ github.workspace }}
          echo "Running latex"
          ls "${GITHUB_WORKSPACE}"/.github/latexcompile.sh
          ls "${GITHUB_WORKSPACE}"/main.tex
          
