name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Compile latex
        run: |
          ls W${{ github.workspace }}/.github/workflows/W
          echo "Running latex"
          echo ${{ GITHUB_WORKSPACE }}
          ls

          
