name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile latex
        run: |
          ls ${{ github.workspace }}/.github/workflows
          echo "Running latex"
          echo ${{ github.workspace }}
          ls

          
