name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile latex
        run: |
          echo "Running latex"
          chmod +x latexcompile
          ./latexcompile -b -r -g -s main.tex


          
