name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: latexcompile + delete extra files
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: ./latexcompile 
          args: -r -b -g 
