name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: latexcombile.sh
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: ./latexcompile 
          root_file: main.tex
          args: -r -b -g 
